import os
from typing import List, Dict, Any
from pydantic import BaseModel, Field
from rag.vectorstore import VectorStore
from llm.gemini import generate_text
from backend.config import settings

class AgentState(BaseModel):
    sources: List[str] = []
    papers_text: str = ""
    research_notes: str = ""
    reading_notes: str = ""
    critique_notes: str = ""
    final_review: str = ""

class ResearchAgent:
    def run(self, state: AgentState) -> AgentState:
        print("[Agent] Research Agent running: Gathering paper metadata and abstracts...")
        prompt = (
            "You are the Research Agent. Your goal is to survey the papers and extract key metadata, "
            "including the Title, Authors, Publication Year/Context, and a brief 2-sentence summary of the core thesis.\n\n"
            f"Here is the content of the papers:\n{state.papers_text}\n\n"
            "Generate your findings as a clean summary of the papers."
        )
        state.research_notes = generate_text(prompt, model_name=settings.LLM_MODEL)
        return state

class ReadingAgent:
    def run(self, state: AgentState) -> AgentState:
        print("[Agent] Reading Agent running: Extracting detailed methodology, datasets, and metrics...")
        prompt = (
            "You are the Reading Agent. Your goal is to inspect the methodology, architectural details, "
            "datasets used, and key evaluation metrics for each paper.\n\n"
            f"Use the Research Agent's metadata as a guide:\n{state.research_notes}\n\n"
            f"Here is the full text of the papers:\n{state.papers_text}\n\n"
            "Extract and document the models/architectures, datasets, methodologies, and key performance metrics in detail."
        )
        state.reading_notes = generate_text(prompt, model_name=settings.LLM_MODEL)
        return state

class CritiqueAgent:
    def run(self, state: AgentState) -> AgentState:
        print("[Agent] Critique Agent running: Identifying contradictions, gaps, and limitations...")
        prompt = (
            "You are the Critique Agent. Your task is to perform a critical evaluation of the papers. "
            "Identify:\n"
            "1. Major limitations and assumptions made in each paper.\n"
            "2. Contradictions or disagreements (e.g. Paper A says X works best, but Paper B says X is inefficient).\n"
            "3. Untapped research gaps and unaddressed edge cases.\n\n"
            f"Use the Reading Agent's findings:\n{state.reading_notes}\n\n"
            f"Here is the full text of the papers:\n{state.papers_text}\n\n"
            "Provide a critical, comparative critique."
        )
        state.critique_notes = generate_text(prompt, model_name=settings.LLM_MODEL)
        return state

class WritingAgent:
    def run(self, state: AgentState) -> AgentState:
        print("[Agent] Writing Agent running: Synthesizing final literature review report...")
        prompt = (
            "You are the Writing Agent. Your task is to write a comprehensive, academic-grade, professional "
            "literature review synthesizing the work of the other agents. "
            "Organize your review into the following standard sections:\n"
            "1. Introduction (Scope and context of the selected papers)\n"
            "2. Summary of Methodologies & Architectures (Synthesis of models and designs)\n"
            "3. Comparative Critique (Direct contradictions, differing results, limitations)\n"
            "4. Identified Research Gaps & Future Pathways\n"
            "5. Conclusion\n\n"
            "Ground your review in the reports generated by the agents:\n"
            f"- RESEARCH AGENT REPORT:\n{state.research_notes}\n\n"
            f"- READING AGENT REPORT:\n{state.reading_notes}\n\n"
            f"- CRITIQUE AGENT REPORT:\n{state.critique_notes}\n\n"
            "Ensure the final output is written in formal academic tone, structured in Markdown."
        )
        state.final_review = generate_text(prompt, model_name=settings.COMPARE_LLM_MODEL)
        return state

def generate_multi_agent_review_fallback(sources: List[str], error_msg: str = "") -> Dict[str, Any]:
    """
    Locally compiles a fallback literature review using text chunks from the vector store
    when the LLM API quota is exhausted, preventing 500 errors.
    """
    from datetime import datetime
    import re
    from rag.vectorstore import VectorStore
    
    vector_store = VectorStore()
    
    # 1. Compile warning banner
    warning_banner = (
        "# 📝 Workspace Literature Review (Local Compilation)\n\n"
        "> [!WARNING]\n"
        "> **OpenRouter API Error**: The multi-agent workflow encountered an API error. "
        "A local literature review was compiled from representative text chunks as a fallback.\n"
    )
    if error_msg:
        warning_banner += f"> *Details: {error_msg}*\n\n"
    else:
        warning_banner += "\n"
        
    content = [warning_banner]
    
    # 2. Extract section text for each document
    content.append("## 1. Introduction & Workspace Context\n")
    content.append("This review covers the following target research papers ingested in the workspace:\n")
    for src in sources:
        content.append(f"- **{src}**\n")
    content.append("\nBelow are compiled text chunks and methodology segments parsed locally from the documents:\n\n")
    
    # Chapter 2: Summary of Methodologies
    content.append("## 2. Summary of Methodologies & Architectures\n")
    for src in sources:
        content.append(f"### Methodological Outline: {src}\n")
        chunks = vector_store.get_document_chunks(src)
        method_chunks = [c for c in chunks if any(kw in c.lower() for kw in ["method", "architectur", "model", "algorithm", "design"])]
        selected = method_chunks[:3] if method_chunks else chunks[:3]
        if selected:
            for text in selected:
                text_clean = re.sub(r'\s+', ' ', text)[:400].strip()
                content.append(f"> ... {text_clean} ...\n\n")
        else:
            content.append("*No text chunks parsed for this source.*\n\n")
            
    # Chapter 3: Comparative Critique
    content.append("## 3. Comparative Critique & Performance Metrics\n")
    for src in sources:
        content.append(f"### Performance & Limitations: {src}\n")
        chunks = vector_store.get_document_chunks(src)
        critique_chunks = [c for c in chunks if any(kw in c.lower() for kw in ["limit", "accuracy", "performance", "metric", "result", "experi"])]
        selected = critique_chunks[:3] if critique_chunks else chunks[3:6]
        if selected:
            for text in selected:
                text_clean = re.sub(r'\s+', ' ', text)[:400].strip()
                content.append(f"> ... {text_clean} ...\n\n")
        else:
            content.append("*No performance evaluation chunks parsed for this source.*\n\n")

    # Chapter 4: Research Gaps
    content.append("## 4. Identified Research Gaps & Future Directions\n")
    content.append("Based on local analysis, the papers present several areas for future work and research gaps:\n\n")
    for src in sources:
        chunks = vector_store.get_document_chunks(src)
        gap_chunks = [c for c in chunks if any(kw in c.lower() for kw in ["future", "gap", "conclusi", "unexplored", "extend"])]
        selected = gap_chunks[:2] if gap_chunks else chunks[-2:]
        if selected:
            for text in selected:
                text_clean = re.sub(r'\s+', ' ', text)[:300].strip()
                content.append(f"- *{src}*: ... {text_clean} ...\n")
        else:
            content.append(f"- *{src}*: Future work details omitted.\n")
    content.append("\n")
    
    # Chapter 5: Conclusion
    content.append("## 5. Conclusion\n")
    content.append("This document compiles key insights from the workspace papers. While the multi-agent LLM workflow was temporarily throttled by API rate limits, these structured snippets provide direct textual context for comparative analysis.")
    
    final_text = "\n".join(content)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"multi_agent_review_local_{timestamp}.md"
    filepath = os.path.join(settings.REPORTS_DIR, filename)
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(final_text)
      
    return {
        "content": final_text,
        "filepath": filepath,
        "agent_logs": {
            "research_notes": "Local fallback gathering completed.",
            "reading_notes": "Local fallback methodology analysis completed.",
            "critique_notes": "Local fallback critique completed."
        }
    }

def generate_multi_agent_review(sources: List[str], vector_store: VectorStore = None) -> Dict[str, Any]:
    """
    Executes the sequential multi-agent graph (Research -> Reading -> Critique -> Writing)
    to synthesize a rich literature review.
    """
    if not vector_store:
        vector_store = VectorStore()

    if not sources:
        return {
            "content": "No papers selected. Please upload and select papers first.",
            "filepath": ""
        }

    # Gather text from selected papers
    papers_data = []
    for source in sources:
        chunks = vector_store.get_document_chunks(source)
        if chunks:
            full_text = "\n\n".join(chunks)
            clipped_text = full_text[:40000] # Cap paper length to prevent token overflow
            papers_data.append(f"--- START OF PAPER: {source} ---\n{clipped_text}\n--- END OF PAPER: {source} ---")

    combined_papers_text = "\n\n".join(papers_data)

    # Initialize agent state
    state = AgentState(sources=sources, papers_text=combined_papers_text)

    # Sequential graph execution
    try:
        research_agent = ResearchAgent()
        reading_agent = ReadingAgent()
        critique_agent = CritiqueAgent()
        writing_agent = WritingAgent()

        state = research_agent.run(state)
        state = reading_agent.run(state)
        state = critique_agent.run(state)
        state = writing_agent.run(state)

        # Save final review to reports/ directory
        from datetime import datetime
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"multi_agent_review_{timestamp}.md"
        filepath = os.path.join(settings.REPORTS_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(state.final_review)

        return {
            "content": state.final_review,
            "filepath": filepath,
            "agent_logs": {
                "research_notes": state.research_notes,
                "reading_notes": state.reading_notes,
                "critique_notes": state.critique_notes
            }
        }
    except Exception as e:
        print(f"Exception during multi-agent review generation: {e}")
        return generate_multi_agent_review_fallback(sources, error_msg=str(e))

